---
title: "Testando Modelos"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.width = 10, fig.height = 5.2)


library(tidyverse)
library(lubridate)
library(janitor)
library(modelr)
library(zoo)
library(forecast)
library(gridExtra)
library(kableExtra)


source('counterfactual_energy.R', encoding = 'UTF-8')
theme_set(theme_bw())
```

## Objetivo

Relatório tem como objetivo testar o modelo **BSM** utilizado para contrafactual do consumo de energia. 


```{r, include = FALSE, warning = FALSE}
energy <- read_csv2("../input/energia_data.csv") %>% 
    rename(ramo = `Ramo de atividade`) %>% 
    mutate(Estado = iconv(Estado, from = "UTF-8", to = "ASCII//TRANSLIT") %>% 
               trimws()) %>% 
    clean_names() %>% 
    mutate(data = as.Date(data, "%d/%m/%Y")) %>% 
    arrange(data, classe, ramo) %>% 
    group_by(data, estado, classe) %>% 
    summarise(consumo = sum(consumo_m_wm))

bsm_model <- counterfact_model(energy)
```


```{r echo=FALSE, warning=FALSE, message=FALSE}
rquadrado <- function(UF) {
    
    modelo <- bsm_model[[UF]]
    
    # fitted x observed
    datas <- seq.Date(from = as.Date("2018-07-01"), 
                      to   = as.Date("2020-02-01"),
                      by   = "month")
    
    fitted_vals <- fitted(modelo)
    
    # build df
    df <- tibble(date     = datas,
                 Fitted   = fitted_vals[, 1] + fitted_vals[, 2] + fitted_vals[,3],                    Observed = modelo$data %>% as.numeric())

    #Calculating R2
    rss <- sum((df$Fitted - df$Observed) ^ 2)          ## residual sum of squares
    tss <- sum((df$Observed - mean(df$Observed)) ^ 2)  ## total sum of squares
    rsq <- 1 - rss/tss

    print(paste0("Estado: ", UF, ", R2: ", rsq))
  
}


teste_modelos <- function(UF){
    
    # modelo
    modelo <- bsm_model[[UF]]
    
    # fitted x observed
    datas <- seq.Date(from = as.Date("2018-07-01"), 
                      to   = as.Date("2020-02-01"),
                      by   = "month")
    
    fitted_vals <- fitted(modelo)
    
    # build df
    df <- tibble(date     = datas,
                 Fitted   = fitted_vals[, 1] + fitted_vals[, 2] + fitted_vals[, 3], 
                 Observed = modelo$data %>% as.numeric())

    # plot componentes
    plot <- autoplot(modelo$data) +
      autolayer(fitted(modelo)) +
      ggtitle(UF) +
      ylab("Energy Monthly Consumption") +
      theme(plot.margin = unit(c(0.2,0.8,0.2,0.2), "cm"))
    
    # plot
    plot_fit_sa <- ggplot(df, mapping = aes(x = date)) + 
      geom_line(aes(y = Observed, color = 'black')) +
      geom_line(aes(y = Fitted, color = 'red')) +
      ggtitle(UF) +
      scale_color_manual(values = c('black', 'red'), name = "",
                         labels = c("Observed", "Fitted")) + 
      ylab("Energy Monthly Consumption") + xlab("Time") +
      theme(plot.margin = unit(c(0.2,0.2,0.2,0.8), "cm"))
    
    return(invisible(grid.arrange(plot, plot_fit_sa, ncol = 2)))
}


print_all <- function(UF) {
  
    rquadrado(UF)
    checkresiduals(bsm_model[[UF]])
    teste_modelos(UF)
    
}

nome_estados <- unique(energy$estado)
list_plots   <- map(nome_estados, print_all)
```
